import { defineConfig, globalIgnores } from 'eslint/config';
import pluginVue from 'eslint-plugin-vue';
import { defineConfigWithVueTs, vueTsConfigs } from '@vue/eslint-config-typescript';
import globals from 'globals';

/**
 * ESLint for the Vue boilerplate.
 *
 * This app had no linting at all, so the first run reported a backlog rather
 * than a regression. The rules below are the ones that catch mistakes the
 * compiler cannot: `vue-tsc` never sees inside a template, so an undefined
 * component, a missing `:key`, a mutated prop or a duplicate attribute all
 * build green and fail at runtime.
 *
 * Deliberately NOT enabled: the stylistic half of `vue/recommended` (attribute
 * order, self-closing tags, per-line attribute counts). It is formatting, it
 * would rewrite most of the templates, and reviewing that diff would bury the
 * real findings.
 */
export default defineConfigWithVueTs(
  defineConfig([
    globalIgnores([
      'dist/**',
      'dist-ssr/**',
      'node_modules/**',
      'playwright-report/**',
      'test-results/**',
      // Generated by predev/prebuild and gitignored — linting it reports on a
      // file nobody edits, and it does not exist on a clean checkout.
      'src/locales/_registry.ts',
    ]),
  ]),

  pluginVue.configs['flat/essential'],
  vueTsConfigs.recommended,

  {
    files: ['**/*.{js,mjs,cjs,ts,mts,tsx,vue}'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      // Underscore-prefixed names are the conventional "declared on purpose,
      // deliberately unused" marker. Matches the Next boilerplate.
      // `ignoreRestSiblings` covers the omit-by-destructuring idiom
      // (`const { database: _d, ...rest } = options`), where the named keys
      // exist precisely so that `rest` does not contain them.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
      // `any` is a warning, not an error: the backlog is real but it is not a
      // reason to fail a build that was green yesterday. New code should still
      // avoid it.
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },

  {
    files: ['**/*.vue'],
    rules: {
      // False positives only. The rule guards against Vue 2's `{{ x | filter }}`
      // syntax, which Vue 3 removed outright — but its parser also reads the
      // `|` in a TypeScript union assertion as a filter pipe, so
      // `:product="product as Product | Cluster"` is reported as a deprecated
      // filter. Every hit in this app is such a cast, and a genuine Vue 2
      // filter would not render at all in Vue 3, so the rule has nothing left
      // to catch here.
      'vue/no-deprecated-filter': 'off',
    },
  },

  {
    // Node-side files: the Express server, build scripts and config.
    files: ['server.js', 'scripts/**/*.{js,mjs}', '*.config.{js,ts,mjs}', 'src/server/**/*.{js,ts}'],
    languageOptions: { globals: globals.node },
  },
);
