// AUTO-GENERATED by scripts/build-locales-registry.mjs
// DO NOT EDIT — run `npm run locales:build` instead.

import enAccountIconAndMenu from './en/AccountIconAndMenu.json';
import enActionCode from './en/ActionCode.json';
import enAddToCart from './en/AddToCart.json';
import enAddToFavorite from './en/AddToFavorite.json';
import enAddressCard from './en/AddressCard.json';
import enAddressSelector from './en/AddressSelector.json';
import enBreadcrumbs from './en/Breadcrumbs.json';
import enCartBonusItems from './en/CartBonusItems.json';
import enCartCarriers from './en/CartCarriers.json';
import enCartIconAndSidebar from './en/CartIconAndSidebar.json';
import enCartItem from './en/CartItem.json';
import enCartOverview from './en/CartOverview.json';
import enCartPaymethods from './en/CartPaymethods.json';
import enCartSummary from './en/CartSummary.json';
import enClusterCard from './en/ClusterCard.json';
import enClusterConfigurator from './en/ClusterConfigurator.json';
import enClusterOptions from './en/ClusterOptions.json';
import enCompanySwitcher from './en/CompanySwitcher.json';
import enDeliveryDate from './en/DeliveryDate.json';
import enErrorPages from './en/ErrorPages.json';
import enFavoriteListDetails from './en/FavoriteListDetails.json';
import enFavoriteListItem from './en/FavoriteListItem.json';
import enFavoriteLists from './en/FavoriteLists.json';
import enForgotPassword from './en/ForgotPassword.json';
import enGridFilters from './en/GridFilters.json';
import enGridPagination from './en/GridPagination.json';
import enGridToolbar from './en/GridToolbar.json';
import enItemStock from './en/ItemStock.json';
import enItemsOverview from './en/ItemsOverview.json';
import enLoginForm from './en/LoginForm.json';
import enMenu from './en/Menu.json';
import enOrderActions from './en/OrderActions.json';
import enOrderBonusItems from './en/OrderBonusItems.json';
import enOrderItemCard from './en/OrderItemCard.json';
import enOrderList from './en/OrderList.json';
import enOrderShipments from './en/OrderShipments.json';
import enOrderSummary from './en/OrderSummary.json';
import enOrderTotals from './en/OrderTotals.json';
import enPriceToggle from './en/PriceToggle.json';
import enProductBulkPrices from './en/ProductBulkPrices.json';
import enProductBundles from './en/ProductBundles.json';
import enProductCard from './en/ProductCard.json';
import enProductDownloads from './en/ProductDownloads.json';
import enProductGallery from './en/ProductGallery.json';
import enProductGrid from './en/ProductGrid.json';
import enProductPrice from './en/ProductPrice.json';
import enProductSlider from './en/ProductSlider.json';
import enProductTabs from './en/ProductTabs.json';
import enProductVideos from './en/ProductVideos.json';
import enPurchaseAuthorizationConfigurator from './en/PurchaseAuthorizationConfigurator.json';
import enPurchaseAuthorizationRequests from './en/PurchaseAuthorizationRequests.json';
import enQuoteActions from './en/QuoteActions.json';
import enRegisterForm from './en/RegisterForm.json';
import enSearchBar from './en/SearchBar.json';
import enUserDetails from './en/UserDetails.json';
import nlAccountIconAndMenu from './nl/AccountIconAndMenu.json';
import nlActionCode from './nl/ActionCode.json';
import nlAddToCart from './nl/AddToCart.json';
import nlAddToFavorite from './nl/AddToFavorite.json';
import nlAddressCard from './nl/AddressCard.json';
import nlAddressSelector from './nl/AddressSelector.json';
import nlBreadcrumbs from './nl/Breadcrumbs.json';
import nlCartBonusItems from './nl/CartBonusItems.json';
import nlCartCarriers from './nl/CartCarriers.json';
import nlCartIconAndSidebar from './nl/CartIconAndSidebar.json';
import nlCartItem from './nl/CartItem.json';
import nlCartOverview from './nl/CartOverview.json';
import nlCartPaymethods from './nl/CartPaymethods.json';
import nlCartSummary from './nl/CartSummary.json';
import nlClusterCard from './nl/ClusterCard.json';
import nlClusterConfigurator from './nl/ClusterConfigurator.json';
import nlClusterOptions from './nl/ClusterOptions.json';
import nlCompanySwitcher from './nl/CompanySwitcher.json';
import nlDeliveryDate from './nl/DeliveryDate.json';
import nlErrorPages from './nl/ErrorPages.json';
import nlFavoriteListDetails from './nl/FavoriteListDetails.json';
import nlFavoriteListItem from './nl/FavoriteListItem.json';
import nlFavoriteLists from './nl/FavoriteLists.json';
import nlForgotPassword from './nl/ForgotPassword.json';
import nlGridFilters from './nl/GridFilters.json';
import nlGridPagination from './nl/GridPagination.json';
import nlGridToolbar from './nl/GridToolbar.json';
import nlItemStock from './nl/ItemStock.json';
import nlItemsOverview from './nl/ItemsOverview.json';
import nlLoginForm from './nl/LoginForm.json';
import nlMenu from './nl/Menu.json';
import nlOrderActions from './nl/OrderActions.json';
import nlOrderBonusItems from './nl/OrderBonusItems.json';
import nlOrderItemCard from './nl/OrderItemCard.json';
import nlOrderList from './nl/OrderList.json';
import nlOrderShipments from './nl/OrderShipments.json';
import nlOrderSummary from './nl/OrderSummary.json';
import nlOrderTotals from './nl/OrderTotals.json';
import nlPriceToggle from './nl/PriceToggle.json';
import nlProductBulkPrices from './nl/ProductBulkPrices.json';
import nlProductBundles from './nl/ProductBundles.json';
import nlProductCard from './nl/ProductCard.json';
import nlProductDownloads from './nl/ProductDownloads.json';
import nlProductGallery from './nl/ProductGallery.json';
import nlProductGrid from './nl/ProductGrid.json';
import nlProductPrice from './nl/ProductPrice.json';
import nlProductSlider from './nl/ProductSlider.json';
import nlProductTabs from './nl/ProductTabs.json';
import nlProductVideos from './nl/ProductVideos.json';
import nlPurchaseAuthorizationConfigurator from './nl/PurchaseAuthorizationConfigurator.json';
import nlPurchaseAuthorizationRequests from './nl/PurchaseAuthorizationRequests.json';
import nlQuoteActions from './nl/QuoteActions.json';
import nlRegisterForm from './nl/RegisterForm.json';
import nlSearchBar from './nl/SearchBar.json';
import nlUserDetails from './nl/UserDetails.json';

export const registry = {
  en: {
    AccountIconAndMenu: enAccountIconAndMenu,
    ActionCode: enActionCode,
    AddToCart: enAddToCart,
    AddToFavorite: enAddToFavorite,
    AddressCard: enAddressCard,
    AddressSelector: enAddressSelector,
    Breadcrumbs: enBreadcrumbs,
    CartBonusItems: enCartBonusItems,
    CartCarriers: enCartCarriers,
    CartIconAndSidebar: enCartIconAndSidebar,
    CartItem: enCartItem,
    CartOverview: enCartOverview,
    CartPaymethods: enCartPaymethods,
    CartSummary: enCartSummary,
    ClusterCard: enClusterCard,
    ClusterConfigurator: enClusterConfigurator,
    ClusterOptions: enClusterOptions,
    CompanySwitcher: enCompanySwitcher,
    DeliveryDate: enDeliveryDate,
    ErrorPages: enErrorPages,
    FavoriteListDetails: enFavoriteListDetails,
    FavoriteListItem: enFavoriteListItem,
    FavoriteLists: enFavoriteLists,
    ForgotPassword: enForgotPassword,
    GridFilters: enGridFilters,
    GridPagination: enGridPagination,
    GridToolbar: enGridToolbar,
    ItemStock: enItemStock,
    ItemsOverview: enItemsOverview,
    LoginForm: enLoginForm,
    Menu: enMenu,
    OrderActions: enOrderActions,
    OrderBonusItems: enOrderBonusItems,
    OrderItemCard: enOrderItemCard,
    OrderList: enOrderList,
    OrderShipments: enOrderShipments,
    OrderSummary: enOrderSummary,
    OrderTotals: enOrderTotals,
    PriceToggle: enPriceToggle,
    ProductBulkPrices: enProductBulkPrices,
    ProductBundles: enProductBundles,
    ProductCard: enProductCard,
    ProductDownloads: enProductDownloads,
    ProductGallery: enProductGallery,
    ProductGrid: enProductGrid,
    ProductPrice: enProductPrice,
    ProductSlider: enProductSlider,
    ProductTabs: enProductTabs,
    ProductVideos: enProductVideos,
    PurchaseAuthorizationConfigurator: enPurchaseAuthorizationConfigurator,
    PurchaseAuthorizationRequests: enPurchaseAuthorizationRequests,
    QuoteActions: enQuoteActions,
    RegisterForm: enRegisterForm,
    SearchBar: enSearchBar,
    UserDetails: enUserDetails,
  },
  nl: {
    AccountIconAndMenu: nlAccountIconAndMenu,
    ActionCode: nlActionCode,
    AddToCart: nlAddToCart,
    AddToFavorite: nlAddToFavorite,
    AddressCard: nlAddressCard,
    AddressSelector: nlAddressSelector,
    Breadcrumbs: nlBreadcrumbs,
    CartBonusItems: nlCartBonusItems,
    CartCarriers: nlCartCarriers,
    CartIconAndSidebar: nlCartIconAndSidebar,
    CartItem: nlCartItem,
    CartOverview: nlCartOverview,
    CartPaymethods: nlCartPaymethods,
    CartSummary: nlCartSummary,
    ClusterCard: nlClusterCard,
    ClusterConfigurator: nlClusterConfigurator,
    ClusterOptions: nlClusterOptions,
    CompanySwitcher: nlCompanySwitcher,
    DeliveryDate: nlDeliveryDate,
    ErrorPages: nlErrorPages,
    FavoriteListDetails: nlFavoriteListDetails,
    FavoriteListItem: nlFavoriteListItem,
    FavoriteLists: nlFavoriteLists,
    ForgotPassword: nlForgotPassword,
    GridFilters: nlGridFilters,
    GridPagination: nlGridPagination,
    GridToolbar: nlGridToolbar,
    ItemStock: nlItemStock,
    ItemsOverview: nlItemsOverview,
    LoginForm: nlLoginForm,
    Menu: nlMenu,
    OrderActions: nlOrderActions,
    OrderBonusItems: nlOrderBonusItems,
    OrderItemCard: nlOrderItemCard,
    OrderList: nlOrderList,
    OrderShipments: nlOrderShipments,
    OrderSummary: nlOrderSummary,
    OrderTotals: nlOrderTotals,
    PriceToggle: nlPriceToggle,
    ProductBulkPrices: nlProductBulkPrices,
    ProductBundles: nlProductBundles,
    ProductCard: nlProductCard,
    ProductDownloads: nlProductDownloads,
    ProductGallery: nlProductGallery,
    ProductGrid: nlProductGrid,
    ProductPrice: nlProductPrice,
    ProductSlider: nlProductSlider,
    ProductTabs: nlProductTabs,
    ProductVideos: nlProductVideos,
    PurchaseAuthorizationConfigurator: nlPurchaseAuthorizationConfigurator,
    PurchaseAuthorizationRequests: nlPurchaseAuthorizationRequests,
    QuoteActions: nlQuoteActions,
    RegisterForm: nlRegisterForm,
    SearchBar: nlSearchBar,
    UserDetails: nlUserDetails,
  },
} as const;

export type RegistryLocale = keyof typeof registry;
export type RegistryNamespace = keyof typeof registry['en'];
